name: Production CD

on:
  workflow_run:
    workflows: ["Production CI"]
    branches:
      - main
    types:
      - completed

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker requirements
        uses: dawidd6/action-download-artifact@v2
        with:
          name: docker requirements
          workflow: product-ci.yml
          workflow-conclusion: success

      - name: Login to Docker Hub
        uses: docker/login-action/@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-server:latest