name: Production CD

on:
  workflow_run:
    workflows: ["Production CI"]
    types:
      - completed

  push:
    branches: ["main"]

jobs:

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Docker result
        uses: actions/download-artifact@v3
        with:
          name: docker requirements

      - name: Login to Docker Hub
        uses: docker/login-action/@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-server:latest